### ISSUE TITLE
UnitOfWork

### ISSUE THREAD

**Issue by ReactiveTurtle** [Rebace/EF#1]
UnitOfWork это часть инфраструктуры, как ты помнишь инфраструктура отвечает за связывание различных компонентов приложения (БД, сторонний сервис, логирование).
Так же с UnitOfWork, это связывание приложения с EF (БД), в нём ты обращаешься к EF, чтобы применить изменения к базе
Помести её в инфраструктуру. Папку лучше назвать UoW

**Comment by Rebace** [comment]
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-5f3d6e8214bc7c80088b357d414c029a7726636107ef428dac6e9e8564bd588b

**Comment by Rebace** [comment]
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-5f3d6e8214bc7c80088b357d414c029a7726636107ef428dac6e9e8564bd588b
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-b84b0f0d61100e0deb204ec78baff9a80d0ddb82b9dcabf2b324af9d9f464f30
