### ISSUE TITLE
Dto

### ISSUE THREAD

**Issue by ReactiveTurtle** [Rebace/EF#2]
Предисловие: в доменной области мы описываем предметную область приложения
Dto - это описание структур, которые мы отправляем клиенту по запросу.
Да, Dto это понятное название, но так как мы дальше будем работать с другим проектом, то лучше пока попрактикуемся с тем, как будем называть папки. В данном случае лучше назвать Api.MessageContracts
Из этого название сразу видно, что он используется в Api и при это содержит структуры (а именно контракты, договорённости), которые описывают отдаваемые данные в ответ на запрос

**Comment by ReactiveTurtle** [comment]
Для ToTodoDto лучше сделать отдельный статический класс с extension method
И лучше назвать его просто Map()

**Comment by Rebace** [comment]
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-eb13b3ce1942dd2d9274d9750af1365878d752c583c478e3947fa07cbd0b2c27
