### ISSUE TITLE
Репозиторий

### ISSUE THREAD

**Issue by ReactiveTurtle** [Rebace/EF#3]
Метод Get не подойдёт, слишком неинформативное название
Больше подойдёт GetById, так сразу понятно что мы должны передать в метод

**Comment by ReactiveTurtle** [comment]
В методе Delete не должно происходить ничего, кроме удаления (да, получать тоже можно)
То есть в Delete ты должен передавать именно сущность, которую ты хочешь удалить
А получаешь ты её в методе контроллера. Там ты её спокойной сможешь обработать
Вдруг у тебя нет такой сущности по Id?
Тогда тебе в контроллере надо вернуть нужный код ошибки (в данном случае 404), но так как у тебя получение сразу в Delete ты проверить этого не сможешь (да, можно усложнить метод Delete, но зачем, если можно сделать проще и понятнее)
А когда ты уже убедился, что сущность есть в базе, то смело можно вызвать метод удаления

**Comment by ReactiveTurtle** [comment]
Console.WriteLine в Delete нужно убрать

**Comment by Rebace** [comment]
https://github.com/Rebace/EF/issues/3#issue-1217599950
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-c8fa1e0b2c19b5504690afba4bed4d7e734af63f1f74c16d9ca4039e9cacfba3R32

https://github.com/Rebace/EF/issues/3#issuecomment-1111213372
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-6780d07d2b4c51532863d6472c84e21f8050eb27f1b2ffdf65b110f8708606e4L42

https://github.com/Rebace/EF/issues/3#issuecomment-1111216008
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-c8fa1e0b2c19b5504690afba4bed4d7e734af63f1f74c16d9ca4039e9cacfba3R72
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-6780d07d2b4c51532863d6472c84e21f8050eb27f1b2ffdf65b110f8708606e4L35
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-d8e4cb3ff659c5c1e416d9a2cb2e3b4a6df051c86804375f30e5a79d09fcc22bR82

https://github.com/Rebace/EF/issues/3#issuecomment-1111216787
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-6780d07d2b4c51532863d6472c84e21f8050eb27f1b2ffdf65b110f8708606e4R17

https://github.com/Rebace/EF/issues/3#issuecomment-1111217305
https://github.com/Rebace/EF/commit/63321f54f582f93aa6832b54e0a79d0f9e3404ac#diff-6780d07d2b4c51532863d6472c84e21f8050eb27f1b2ffdf65b110f8708606e4L36
